import type { Metadata } from "next";
import { Sora } from "next/font/google";
import ModeButton from "@/components/UI/modeButton/ModeButton";
import "./globals.css";
import Nav from "@/components/layout/nav/Nav";
import Main from "@/components/layout/main/Main";

const fontFam = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontFam.className}>
        <ModeButton />
        <Nav />
        <Main>{children}</Main>
      </body>
    </html>
  );
}
